# Generated by Django 5.2.8 on 2025-12-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="preview_image",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="number_of_views",
            new_name="views_count",
        ),
    ]
